### ISSUE TITLE
🐞 [Bug]: Port audit findings for generic template to evm template

### ISSUE THREAD

**Issue by ozgunozerk** [OpenZeppelin/polkadot-runtime-templates#237]
### templates

- [ ] Generic Runtime Template
- [X] Evm Template

### What happened?

Below is the recap of the audit findings and the related issues & PRs:

- [x]  3.2.1 XCM delivery fees (no issue is submitted at that time due to visibility) → https://github.com/OpenZeppelin/polkadot-runtime-templates/pull/159/files
    - [x]  tracking in #223 
- [x]  3.2.2 no xcm delivery fees #154→ https://github.com/OpenZeppelin/polkadot-runtime-templates/pull/156
- [x]  3.2.3 incorrect weights for xcm and message queue #135 → https://github.com/OpenZeppelin/polkadot-runtime-templates/pull/153
- [ ]  3.2.4 insufficient benchmarking #138 → https://github.com/OpenZeppelin/polkadot-runtime-templates/pull/149

- [x]  4.1 filtering #141 → https://github.com/OpenZeppelin/polkadot-runtime-templates/pull/146
- [x]  4.2 benchmarking #142
- [x]  4.3 improve docs for runtime parameters #143 → https://github.com/OpenZeppelin/polkadot-runtime-templates/pull/167
    - [x]  also documented new stuff in `impl fp_rpc::EthereumRuntimeRPCApi<Block> for Runtime`
    - [x] removed `const MAX_POV_SIZE` declaration, since it is available to import from polkadot-sdk
- [x]  4.4 remove link to archived repo #144 → https://github.com/OpenZeppelin/polkadot-runtime-templates/pull/146

### Expected behavior

We should port these fixes to our evm template as well.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

**Comment by ggonzalez94** [comment]
@ozgunozerk I'm marking this as closed since I don't know of any finding from the generic templates that we haven't ported to the evm. Feel free to re-open if I missed something
